### ISSUE TITLE
resources/archived endpoint isn't returning results / is 404

### ISSUE THREAD

**Issue by ethanteague** [resourceguru/api-docs#28]
Hi.  resources/ works, but resources/archived does not (I do have archived resources).  Also tried doing /resources?archived=1, but without success.  Thanks for your help with this.

**Comment by roginator** [comment]
Oh wow, that's not good! We'll look into that and get back to you as soon as we can. Apologies for the inconvenience in the meantime and thanks for letting us know!

**Comment by ethanteague** [comment]
Thanks, @roginator.

**Comment by roginator** [comment]
Hi @ethanteague, we have now fixed that so please give it a try now. Once again, sorry for the inconvenience.

Cheers, Andrew
