### ISSUE TITLE
Accessing ResourceGuru API from frontend javascript application

### ISSUE THREAD

**Issue by nahn** [resourceguru/api-docs#4]
Hello,

I have read your docs regarding the API.

Here's my issue:

I have a node.js server that uses https and serves an angular.js application.
The application's url is: https://127.0.0.1:9090.

I have added my application's url as the "redirect URI" on the ResourceGuru developer site, and the initial authorization and redirection works.

After authorizing the app, it redirects me to my localhost url (127.0.0.1...) and appends the access_token, token_type, and expires_in parameters to it.

So far so good.

Now when I request https://api.resourceguruapp.com/v1/accounts from the ResourceGuru api (if you know angular.js, for this request I used $http.get()), it gives me the following error in the console:
No 'Access-Control-Allow-Origin' header is present on the requested resource."

As a possible solution, I tried using a jsonp method, and the cross-domain error doesn't show up anymore, but the request fails.

Could you update the documentation to show how to use the API using a javascript / frontend client? It would help a lot.

Thank you.

**Comment by sirkitree** [comment]
Still no javascript documentation?

**Comment by roginator** [comment]
Sorry sirkitree, I'm afraid we don't have any right now.
