### ISSUE TITLE
Refresh tokens for offline apps

### ISSUE THREAD

**Issue by mergulhao** [resourceguru/api-docs#44]
Hi Guys,

I'm developing a server-side app (not one where a regular user login doing oauth with you). I need to pull data from your API on a daily basis. As your refresh token policy works nowadays I'm forced to use login with user credentials, since, everytime I refresh an access token my old refresh token is revoked.

I think that makes sense you do something like google apis, where they can provide a refresh token for offline apps, where the refresh token is only revoked if the user revokes from his account.

Reference: http://stackoverflow.com/questions/8953983/do-google-refresh-tokens-expire

My 2 cents. Thanks.

**Comment by HendrikLouw** [comment]
Hi @mergulhao we've added refresh tokens, please see https://github.com/resourceguru/api-docs/blob/master/sections/authentication.md for more information.
