### ISSUE TITLE
Update of booking with api clears project_id 

### ISSUE THREAD

**Issue by MarekGrzebyk** [resourceguru/api-docs#45]
Hi Guys, 
I use APIs to integrate resourceguru with our internal CRM. Making that integration even deeper I have come across a problem with update of bookings. It seems that when you do update booking with api (HTTP PUT) to change for example 'details' description, it clears **'project_id**' field of booking with null. In result, the update breaks the link between a project and its bookings. 

**_Example:_**
Object sent with http put:

`'{"id":4829509,"client_id":144513,"project_id":362257,"resource_id":51226,"notes":"Dni: 3,0 |Typ: Wdro?enie |Data fakt: 2016-05-28","details":"Dni: 3,0 |Typ: Wdrożenie |Data fakt: 2016-05-28","start_date":"2016-06-13","end_date":"2016-06-17","refreshable":false,"created_at":"2016-05-20T11:03:10.000Z","updated_at":"2016-05-20T11:28:43.000Z","booker":{"id":8495,"name":"Marek Grzebyk","email":"marek.grzebyk@h.com.pl","color":"#BFBFBF"},"durations":[{"date":"2016-06-13","duration":480,"start_time":null,"end_time":null,"waiting":false},{"date":"2016-06-14","duration":480,"start_time":null,"end_time":null,"waiting":false},{"date":"2016-06-15","duration":480,"start_time":null,"end_time":null,"waiting":false},{"date":"2016-06-16","duration":480,"start_time":null,"end_time":null,"waiting":false},{"date":"2016-06-17","duration":480,"start_time":null,"end_time":null,"waiting":false}]}'`

the response:
`'{"id":4829509,"client_id":144513,"project_id":null,"resource_id":51226,"notes":"Dni: 3,0 |Typ: Wdro?enie |Data fakt: 2016-05-28","details":"Dni: 3,0 |Typ: Wdro?enie |Data fakt: 2016-05-28","start_date":"2016-06-13","end_date":"2016-06-17","refreshable":false,"created_at":"2016-05-20T11:03:10.000Z","updated_at":"2016-05-20T11:38:46.000Z","booker":{"id":8495,"name":"Marek Grzebyk","email":"marek.grzebyk@h.com.pl","color":"#BFBFBF"},"durations":[{"date":"2016-06-13","duration":480,"start_time":null,"end_time":null,"waiting":false},{"date":"2016-06-14","duration":480,"start_time":null,"end_time":null,"waiting":false},{"date":"2016-06-15","duration":480,"start_time":null,"end_time":null,"waiting":false},{"date":"2016-06-16","duration":480,"start_time":null,"end_time":null,"waiting":false},{"date":"2016-06-17","duration":480,"start_time":null,"end_time":null,"waiting":false}],"removed_availability_dates":[]}'`

Could you take a look at this issue please?
Best regards :)

**Comment by Ashton101** [comment]
Hi MarekGrzebyk

You can only pass a client_id or project_id but not both in the request as per the docs here https://github.com/resourceguru/api-docs/blob/master/endpoints/bookings.md. Please supply either one or the other.

Regards

**Comment by MarekGrzebyk** [comment]
Thanks a lot! 
As you know solution it sounds so logical.

Best.
