### ISSUE TITLE
403 error on 'Reports' Endpoint

### ISSUE THREAD

**Issue by levizimmerman** [resourceguru/api-docs#49]
**Issue**
When using https://api.resourceguruapp.com/v1/example-corp/reports/resources?start_date=2016-10-31&end_date=2016-11-04&access_token=1234abcd1234&token_type=bearer, I get a 403 Forbidden error. This goes up for all reports endpoints (clients, projects, resources).

**Assumption**
- Logged in as an administrator user;
- All other API endpoints work (bookings, resources, projects, etc.);
- Include all required parameters (start_date, end_date, access_token, token_type);
- Use GET method with jQuery ($.get);
- Using localhost with SSL;

Is this a known issue or am I doing something wrong?

**Comment by kmckelvin** [comment]
Hi @levizimmerman 

Reports are only available on the Blackbelt and Master plans. Please see our pricing pages at https://secure.resourceguruapp.com/pricing-signup for the feature comparison. If you require reports then the owner of your account can upgrade from the billing page.

Please let us know if there's anything else we can help with.

Regards
Kevin
