### ISSUE TITLE
Is it possible to add "client_id" when creating a Project?

### ISSUE THREAD

**Issue by daaain** [resourceguru/api-docs#5]
I'm investigating the API at the moment and can't try right now, but would it be possible to pass `client_id` as a parameter when creating a Project? Either case, the docs are not clear on this so would be useful to clarify.

Thanks a lot!

**Comment by roginator** [comment]
Hi daaain, I have no idea how we missed your question here - a thousand apologies! I'm guessing that a response 15 months later is pretty useless for you. But, for anyone else who sees this - yes, you can create a project and specify the `client_id`.

Once again, apologies for the ridiculously late reply!

Cheers, Andrew
