### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by banstola** [resourceguru/api-docs#52]
Could the API documentation be done in a proper way. So we can see more organised documentation. This doc works but it is not very friendly.

**Comment by roginator** [comment]
Hi, thanks for the feedback. We realise the documentation is a little basic and do plan to improve it in the future. If you could provide a link or two to some API documentation you like, that would be very useful.

**Comment by banstola** [comment]
For example you can check how woocommerce has done it's API documentation or elm language documentation just to name few. But anyway I do not think this documentation is very developer friendly.

**Comment by roginator** [comment]
OK thanks for the info. I've had a look at what they're using for their documentation and we'll take that into account when we redevelop our docs.
