### ISSUE TITLE
Why the secret is sent as an additional header?

### ISSUE THREAD

**Issue by alberlyeh** [resourceguru/api-docs#57]
Hello, 

I've just started to write a custom app to let Resource Guru (RG) events trigger some custom actions on Office365, but I don't understand why the Secret used to calculate the signature is sent as an additional header.

I would expect to get only the signature, not the secret, which shall be known only by RG and my app. Since the purpose of the signature is to ensure the request has not been tampered with by an external entity, including the secret might nullify it, as the signature could be recalculated. This is quite unlikely to happen, unless a reverse proxy terminating the TLS connection - not directly managed by the user - is in place.

Could someone be so kind to clarify me this point?

**Comment by kmckelvin** [comment]
Hi @alberlyeh 

The secret is a simple mechanism you can use to check that the webhook payload is coming from Resource Guru and not a (potentially malicious) third party. It should be posted across a TLS connection to keep it safe.

The HMAC signature was added by request and is useful for verifying the integrity of the webhook payload data or as a second security check, but generally isn't needed. I agree that it would be more useful if you had the option not to include the secret as part of the request and I've added it as a work item to our product roadmap.

Hope this helps!

**Comment by kmckelvin** [comment]
@monkeypants @alberlyeh you now have an option in your webhooks settings page that will let you turn off sending the `X-ResourceGuru-Secret` header. It will be off by default for new webhooks you create from now on.

Thank you for raising this issue and for the feedback you provided. Please let us know if we can be of any further help!
