### ISSUE TITLE
Error creating new TimeOff Event - 422 (Unprocessable Entity)

### ISSUE THREAD

**Issue by Moristotle** [resourceguru/api-docs#67]
Hi, 

There seems to be an issue with the Create TimeOff/Downtime event endpoint. 

I am attempting to create a TimeOff Event, but I keep receiving a 422 error.
I have debugged the issue and verified that the json-string I'm passing as the request body is identically formatted to the example from the docs. 

![image](https://user-images.githubusercontent.com/43928778/78313568-74c69f80-7557-11ea-8f29-21d2ff38b4df.png)

**Comment by KrofDrakula** [comment]
@Moristotle I see that you have a trailing comma in your field list. This is invalid JSON as per the specs:

https://jsonlint.com/?json={%22property%22:%22value%22,}

**Comment by Moristotle** [comment]
Thanks for the quick reply @KrofDrakula ! :) 
The above code snippet I pasted directly from the TimeOff documentation in this repository. 

I resolved the issue. 
Found out that the issue was that I was passing in a resource_id instead of a user_id when inserting booker_id.
