### ISSUE TITLE
Removed or Archived employees are shown in the report

### ISSUE THREAD

**Issue by SSwartMerkle** [resourceguru/api-docs#71]
Hi, 

I run weekly reporting on the persons placed on projects and I noticed when I remove or archive a person the person is still reported in the particular week. 

For example this week I removed/archived 1 person and run the report the person is still in the output and if no booking against it will report on not utilised.    

The is the corresponding API I use:
https://api.resourceguruapp.com/v1/<Company>/reports/resources?start_date=2020-11-02&end_date=2020-11-06 

The person I remove via the resourceGuru website. 

Is this something of incorrect working or is there a way around this? 

Thanks,
Sander

**Comment by kmckelvin** [comment]
Hi @SSwartMerkle 

Historical data is kept intact in reports when a resource is removed or archived. The resource will only be shown in the report if they have availability in the reported time frame. E.g. if you archive a resource on Tuesday, then request a report for the Wednesday - Friday of the same week, the resource will not be listed.

If you require the data to be completely deleted please [contact customer support](https://resourceguruapp.com/contact-resource-guru) with the details of the account and resource, and we'll be happy to assist further.

Thanks
Kevin
