### ISSUE TITLE
Feature Request: The response when a request fails returns plaintext instead of JSON

### ISSUE THREAD

**Issue by apuri92** [resourceguru/api-docs#72]
If for some reason a resource request goes wrong, only plaintext (eg: "Unauthorized", etc) is returned, as opposed to a JSON object containing the error code and the description. This is inconsistent with the response returned during the authorization process
`
{
	"error":"invalid_grant",
	"error_description":"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."
}
`

**Comment by kmckelvin** [comment]
Hi @apuri92 

Thanks for reaching out about the inconsistent response content type. We're tracking a story for this internally and plan to return JSON responses in all cases - including some other error cases that are currently returning plain text responses. I can't give you a firm date, but we will inform you when it's changed, and include it in a product update post.

Thanks
Kevin
