### ISSUE TITLE
Authentication server redirection error

### ISSUE THREAD

**Issue by apuri92** [resourceguru/api-docs#73]
Is anyone else experiencing too many redirects when using the OAuth protocol for login? I am being redirected between the following URLs and getting the 'too many redirects' error:
* https://app.resourceguruapp.com/oauth/authorize?client_id=redacted&redirect_uri=redacted&response_type=code&state=redacted
* https://app.resourceguruapp.com/login

I cleared my cache and cookies but that didn't help.

**Comment by apuri92** [comment]
It seems like the error happens only if the user is not already logged in to Resource Guru, i.e. if the user is logging in when redirected by my app, then they get stuck in a loop.

**Comment by kmckelvin** [comment]
Hi @apuri92, I believe you've heard back from our customer support since opening this issue and that the issue has been resolved.

Thanks
Kevin
