### ISSUE TITLE
resource_type_id, 422 Unprocessable entity

### ISSUE THREAD

**Issue by I3lutI3ad** [resourceguru/api-docs#79]
I'm trying to make resources from API end point `https://api.resourceguruapp.com/v1/ripusudan/resources`
with payload
```
{
    "first_name": "a",
    "last_name": ".",
    "notes": "asdasd",
    "bookable":true,
    "invite": false,
    "resource_type_id": 1
}
```
I'm using proper tokens and to authenticate, booking and all is working, it's just in this case the response it gives is
```
{
    "resource_type_id": [
        "can't be blank"
    ]
}
```

**Comment by KrofDrakula** [comment]
@I3lutI3ad You need to use the correct `resource_type_id` from the [`resource_types`](https://resourceguruapp.com/docs/api#tag/resource/paths/~1v1~1{account}~1resource_types~1{id}/get) for the account you're creating them for.

**Comment by I3lutI3ad** [comment]
@KrofDrakula Thank you for point me to the API, I thought, the id for person type resource was 1, and I kept on retrying that.
